# Generated by Django 6.0.6 on 2026-06-18 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0002_pais_alter_estudiante_id_alter_numerotelefonico_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pais',
            old_name='numero_de_habitantes',
            new_name='numero_habitantes',
        ),
        migrations.RenameField(
            model_name='pais',
            old_name='numero_de_provincias',
            new_name='numero_provincias',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='administrativo.pais'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='capital',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
